---
- name: Install and configure Apache and MariaDB
  hosts: n01605052-l-2.canadacentral.cloudapp.azure.com
  become: true
  tasks:
    - name: Install Apache web server
      yum:
        name: httpd
        state: present

    - name: Install MariaDB server
      yum:
        name: mariadb-server
        state: present

    - name: Enable Apache service
      service:
        name: httpd
        enabled: yes

    - name: Start Apache service
      service:
        name: httpd
        state: started

    - name: Enable MariaDB service
      service:
        name: mariadb
        enabled: yes

    - name: Start MariaDB service
      service:
        name: mariadb
        state: started

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted

    - name: restart mariadb
      service:
        name: mariadb
        state: restarted
