---
- name: To Manage users and groups
  hosts: n01605052-l-1.canadacentral.cloudapp.azure.com
  vars:
    grouplist1: group10
    grouplist2: group20
    userlist1: user10
    userlist2: user20
  tasks:
    - name: Create group {{ grouplist1 }}
      group:
        name: "{{ grouplist1 }}"
        state: present

    - name: Create group {{ grouplist2 }}
      group:
        name: "{{ grouplist2 }}"
        state: present

    - name: Make user10 with UID 1800 and supplementary membership to group10
      user:
        name: "{{ userlist1 }}"
        uid: 1800
        groups: "{{ grouplist1 }}"
        append: yes

    - name: Make user20 with UID 1900, shell /bin/bash, and home directory under /home
      user:
        name: "{{ userlist2 }}"
        uid: 1900
        shell: /bin/bash
        home: "/home/{{ userlist2 }}"
        groups: "{{ grouplist2 }}"
        append: yes
